language: java

jdk:
  - oraclejdk8

script:
  - ./gradlew clean check --stacktrace

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "PD2ZaZxyrpLDq8dsC+JdfkGg7kEPgmhBzqO+zr+ONBuVe+YDLqsTAUF6J6zXoMF6mgBvkalW/v1nRbDvKJBXhGJdrIqPoQ2yhc7nPH1shzUK6WFptsRsPk2+B45M+FmAjlsSHqCjXIcPmRKykCjgjFyR6DVsik2mPA/C8dINwM2LUsD6eKsed79VHjhrpmqBfIKsvSY1saGfqlGmNzYOFHJ8wHfgjBVUlJmzJzWM49gudW8J27zphP59GjAR1/ZHeYAhE+KQEMUfMKtpFUjZiWvE5kNd+4xgUfXh9mRpwA/RuCJhipgzMTBPxHF4WHHC4pIQDJ5/KeF++L6xzweuBheGvOewWvjSWnPpBsEk3YK6X0SI52OcAApsk1KX+8h58ABU/85DObFpxLsAYTNnePWc6f4a1boV/K2f/RTZBp9U15h9z7474BXIZ7t/IFCZgPZp+v5a15CJrjBq/8g1Yi7f0KGj6ax5vctRaQK5pvIasT1Z0bZLWoRO8WWOkatymkUhBT/aPiVm3PbZeqLgp+tljiSzCF6oF7rQDjbCHsNOAr9Y1+SS/bIu0sLXCgQ4Ji4HGDYpub3v6vRWMW5sv23LR9YsgVXXaehZR1k4hScqbscu6/FfYy5N/2h8IeABNZW3mYnR6zmk1VM4uzHcMkD9iJAc07tPsmrxd4aOaNQ="
    - secure: "fiI2ZFtZ1LRVcZizbbiHCiKrtKkcyzAPZse8quvuB3VumnfqhPTT1hyyRkV3vXP6R6oigdZG67pG2yGvMovHfyMfQfOfTyfyQw/i7xJTTgOkH2NmeTA+SPn/VnZjZPSwyvkDXgxOOjyoa3G7eSTpblzh13247tZppA4ERKyUUmHPDBVL0kktkabQjRltu6vuUT1vLh0j5Lg/A5HRWF22Bkt0NqrmkYbJaDaW40w/f62OonXS8g4LIKolmHFIfhyoMG4Pj1gUAPUl+0mJ6d/CkCYxnRmWSzTvodsYCp+y06e9MXLL95A+2wg/5oUrwOPigwMlWDp0rWgceU9X0wWK6+7I7nWCJb/+Hr+okL/UE62BxnDPWecyvXRsGbXHAx/VXv2dP3f4qi9GMn2NnpgswQZUdFLfBzZTghT9UftaLeUej6rWrnnlEJLr78ZyYPvXVtwXm0oAWH0iA39Nd6OCmV+YIqgnptUzWugHKCbR4/bgs02HvuIfw+bRGEYUshjD3gSZYNYKcuV8TYmFOnQqRXaYm4yosxwX/t6Zp1mH+s6N98OEEYHIwyaQ8hxBKrpAWmVYr0Nzu7rfITNwLkTB2LBHlv3K2zYP8vz8mz3gm5Y6VFEUqbnHLIfLDWw8jy0Q4oZSyzytgrKeQTeI0erku2uOJFzRce6bHmEjRfOLwDM="

branches:
  except:
    - gh-pages

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle
